### ISSUE TITLE
How to create imgui::Image ?

### ISSUE THREAD

**Issue by Athorus** [iolivia/imgui-ggez-starter#12]
First of all, I want to thank you for your great article! It helped me to use imgui with ggez 0.4.4 and it helped me again when I migrated to ggez 0.5.1. It saved me a lot of time for my game ! So maybe you could help me again.

Do you know how to create an "imgui::Image" ? I need this because I want to popup a window showing an Image from a file.

It would be great if we were able to display a "ggez::graphics::Image" inside an imgui Window!

Optional question : Would it be doable to display an animated GIF ?

Thanks.

**Comment by iolivia** [comment]
Hey! really glad it helped! I just added an example on master with loading an image and rendering it in the UI, let me know if that helps 😄 I think gifs *should* be the same, but give it a go and let me know if it doesn't work.

**Comment by Athorus** [comment]
Thank you very much! This is what I need! I'll give you a link to my "little" game when it will be ready to be published. :)

When I try with an animated GIF, only a frozen image is displayed. No sure if it is easily doable. I can live whitout it. ;)

**Comment by iolivia** [comment]
Yeah please send me a link, would love to have a look! Hmm I guess the gif behaviour makes sense, thinking about it now gifs probably need to be handled more like videos than images. Looks like imgui doesn't have a built-in way to play video https://github.com/ocornut/imgui/issues/2422. But I wonder if you can hack it yourself by displaying sequential images in your render loop. For example, break the gif into x frames, load those x textures like the code above, and then in the render loop choose which texture to display based on the time. Let's say you had 10 frames per second, between 0-100ms you show frame1, then 100-200ms frame2, etc.

**Comment by Athorus** [comment]
Thanks, I integrated your code in my game and I have to say it helped me a lot. About 10 steps is needed in order to display a simple image in an ImGui Window ! I wouldn't find myself all these steps.
Yes, an animated GIF is like a video, but I won't put effort on this, because you know, ImGui is a Gui for debugging games.
If my game has some success and I can find someone to create assets, I will take a look about playing video in a game.

Once again, thank you very much !

**Comment by iolivia** [comment]
really glad it helped! 🎉 best of luck with your game!

**Comment by Athorus** [comment]
I've published my game : Le Train Dispatcher !
http://athorus.itch.io/ltd

Tell me what you think about this game, even though your comments are not so nice. 😉 (I need useful comments to evolve the game concepts) 

Go to the menu "Help" to see where I needed to load an image in an ImGui window.

**Comment by iolivia** [comment]
ahhh that is super cool! very satisfying to see the image loading 🎉 

btw you should add some instructions on the itch page for mac that you need to download and then `chmod 755` before you're able to run the executable. Will have a deeper look at the game soon 😄

**Comment by Athorus** [comment]
I'm glad to hear my OsX executable works! :D I compiled it thanks to osxcross as I do not own a Mac.
How should I package the file for OsX ? In a tar.gz like Linux systems, in order to keep 755 ?

Fill free to open a post on itch, it will make the page alive.
