### ISSUE TITLE
IMGUI Display Missing on Certain Portions of Screen

### ISSUE THREAD

**Issue by nsmryan** [iolivia/imgui-ggez-starter#9]
First of all, thank you for this repo- its exactly what I needed after failing in my own attempt to get these libraries to work together.

The problem that I'm having is that on my Ubuntu (x64) installation the IMGUI window shows up and the ball displays as expected, but the contents of the IMGUI window do not draw.
If I move the window around the screen, in certain positions, an area of the IMGUI window does draw, and this portion changes as I slide the window around. Near the bottom left of the ggez window the full IMGUI contents are displayed.

I was able to fix this by setting the line:
    self.imgui.io_mut().display_framebuffer_scale = [2.0, 2.0];
to    
    self.imgui.io_mut().display_framebuffer_scale = [1.0, 1.0];
 
but I was wondering if there is a reason for the scaling here, and whether changing this has some consequences that I should be aware of.

Thank you!

**Comment by nsmryan** [comment]
This screenshot should show the problem:

![Screenshot from 2019-09-01 14-09-07](https://user-images.githubusercontent.com/1892046/64080443-336cc980-ccc2-11e9-84cc-017b10654e07.png)

**Comment by iolivia** [comment]
hey @nsmryan, thanks a lot for the report! ah this is really interesting. I think it might have something to do with the display I am using (retina), just noticed the docs for that property specify that retina displays need to be handled differently. I tried changing it to `1.0` but now it looks wrong on my screen.

```
pub display_framebuffer_scale: [f32; 2]
For retina display or other situations where window coordinates are different from framebuffer coordinates
```

will have a look see what I can find 😄

**Comment by nsmryan** [comment]
I had never heard of retina displays, but it sounds like they have some kind of higher pixel density thing going on?

**Comment by iolivia** [comment]
yep, that's exactly it. so maybe my screen has 2x the pixels, which is why everything looks fine for me with the scale factor of 2. we probably need to figure out what the pixel density of the screen is and calculate the factor based on that.

**Comment by iolivia** [comment]
hey @nsmryan, I had a dig around and I think I might have found the issue. I made a PR for fixing the scale, works for my display, can you grab that branch and see if it works for you? If it does, I'll get that merged.

**Comment by JacobHaig** [comment]
@iolivia Fyi, I'm having the same issue as @nsmryan. I'm currently running at 1440p and @nsmryan answer resolved my issue.

**Comment by iolivia** [comment]
thanks for reporting @JacobHaig, fix was just merged so feel free to grab latest master and let me know if you have any more issues.
